# Multiplicação de 2 Matrizes

Faça um programa que leia duas matrizes A e D de tamanho 3 x 3 e calcule C = A * B

In [2]:
import numpy as np

In [3]:
# definição da matriz A
A = np.zeros((3, 3), dtype=int)
print(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# definição da matriz B
B = np.zeros((3, 3), dtype=int)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# Loop para preencher a matriz A com valores do usuário
for i in range(3):
    for j in range(3):
        # Use o input para ler o valor do usuário e adicioná-lo à matriz
        elemento = int(input("Insira o elemento da posição [{}][{}]: ".format(i, j)))
        A[i][j] = elemento

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Loop para preencher a matriz B com valores do usuário
for i in range(3):
    for j in range(3):
        # Use o input para ler o valor do usuário e adicioná-lo à matriz
        elemento = int(input("Insira o elemento da posição [{}][{}]: ".format(i, j)))
        B[i][j] = elemento

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Use a função dot para multiplicar as matrizes
C = np.dot(A, B)

# Imprime o resultado da multiplicação
print(C)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
