# Procurar valor maior em matriz

Leia uma matriz 4 x 4, imprima a matriz e retorne a localização (linha e a coluna) do maior valor

In [5]:
import numpy as np

In [6]:
matriz = np.zeros((4, 4), dtype=int)
print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
# Loop para preencher a matriz com valores do usuário
for i in range(4):
    for j in range(4):
        # Use o input para ler o valor do usuário e adicioná-lo à matriz
        elemento = int(input("Insira o elemento da posição [{}][{}]: ".format(i, j)))
        matriz[i][j] = elemento

print(matriz)

[[      45       45       78       95]
 [      84       87      556       26]
 [      46       45       56     1521]
 [15151515    15456      546      552]]


In [8]:
# Use a função amax para localizar o maior valor na matriz
maior_valor = np.amax(matriz)

# Imprime o maior valor na matriz
print(maior_valor)

15151515


In [10]:
# Use a função argmax para localizar o índice do maior valor na matriz
indice_maior_valor = np.argmax(matriz)

# Converte o índice em um par (linha, coluna)
linha, coluna = np.unravel_index(indice_maior_valor, matriz.shape)

# Imprime a localização do maior valor na matriz
print("O maior valor está na linha {} e coluna {}".format(linha + 1, coluna + 1))

O maior valor está na linha 4 e coluna 1
