# Procurar valor em matriz

Leia uma matriz 5 x 5 sem valores repetidos. Leia também um valor X . O programa deverá fazer uma busca desse valor na matriz e, ao final, escrever a localização (linha e coluna) ou uma mensagem de ' nao encontrado”.

In [11]:
import numpy as np

In [22]:
# definição da matriz
matriz = np.zeros((3, 3), dtype=int)
print(matriz)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
x = int(input("Introduza um valor para buscar na Matriz: "))
print(x)

4


In [23]:
# Preencher a matriz com valores do usuário
for i in range(len(matriz)):
    for j in range(len(matriz)):
        valor = int(input("Introduza um valor para a posição {}x{}".format(i + 1, j + 1)))
        # Controlo para verificar se o valor introduzido já está na matriz
        while valor in matriz:
            print("Esse valor já foi inserido. Insira outro valor.")
            valor = int(input("Insira um valor para a posição ({}x{}): ".format(i + 1, j + 1)))
        
        matriz[i][j] = valor

print(matriz)

Esse valor já foi inserido. Insira outro valor.
Esse valor já foi inserido. Insira outro valor.
Esse valor já foi inserido. Insira outro valor.
[[ 12  15  45]
 [ 64 456  84]
 [ 94  97   4]]


In [24]:
# procurar por x na matriz
encontrado = False

for i in range(len(matriz)):
    for j in range(len(matriz)):
        if matriz[i][j] == x:
            print("O valor {} foi encontrado na linha {} e coluna {}".format(x, i + 1, j + 1))
            encontrado = True
            break
    if encontrado:
        break

# Se o valor não for encontrado, imprima uma mensagem de erro
if not encontrado:
    print("O valor {} não foi encontrado na matriz.".format(x))


O valor 4 foi encontrado na linha 3 e coluna 3
