# **Matriz 3 x 3**

Leia uma matriz de 3 x 3 elementos. Calcule a soma dos elementos que estão acima da diagonal principal.

In [23]:
import numpy as np

In [24]:
matriz = np.zeros((3, 3), dtype=int)
print(matriz)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
# Loop para preencher a matriz com valores do usuário
for i in range(3):
    for j in range(3):
        # Use o input para ler o valor do usuário e adicioná-lo à matriz
        elemento = int(input("Insira o elemento da posição [{}][{}]: ".format(i, j)))
        matriz[i][j] = elemento

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Use a função triu para acessar os elementos acima da diagonal principal
elementos_acima_diagonal = np.triu(matriz, k=1)

print(elementos_acima_diagonal)

[[0 2 3]
 [0 0 6]
 [0 0 0]]


In [27]:
# Use a função sum para somar os elementos acima da diagonal principal
soma_acima_diagonal = np.sum(elementos_acima_diagonal)

# Imprime a soma dos elementos acima da diagonal principal
print(soma_acima_diagonal)

11
