Usando np.where e criando matriz de zeros como tamanho incógnito.


In [9]:
import numpy as np # 

arr = np.array([[5, 2, 3], [4, 5, 6], [7, 5, 9]])
x = 5

posicoes = np.where(arr == x)
print(list(zip(posicoes[0], posicoes[1])))
print(posicoes)

[(0, 0), (1, 1), (2, 1)]
(array([0, 1, 2]), array([0, 1, 1]))


In [21]:
x = 10 # ou qualquer outro valor desejado
y = 4 # ou qualquer outro valor desejado
matriz = np.zeros((x, y), dtype=int)


print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
