# Matriz - Devolve diagonal inferior

Faça uma função que receba uma matriz de 3 x 3 elementos. Calcule e retorne a soma dos elementos que estão abaixo da diagonal principal.

In [27]:
import numpy as np

In [28]:
def devolve_diagonal_inferior (matriz): 
    diagonal_inferior = np.tril(matriz, k=-1) # k=-1 para a diagonal inferior
    indices = np.nonzero(diagonal_inferior) # retorna os indices dos elementos diferentes de zero
    return diagonal_inferior[indices] # retorna os elementos diferentes de zero

In [29]:
matriz = np.random.randint(100, size=(3, 3))
print(matriz)

[[69 80 70]
 [ 1 37  2]
 [61 35  7]]


In [30]:
print(devolve_diagonal_inferior(matriz))

[ 1 61 35]
