# Matriz transporta

Escreva uma função que recebe uma matriz quadrada de ordem N e calcule a sua transposta (se B é a matriz transposta de A então aij = bji).

In [4]:
import numpy as np

In [5]:
def transposta(matriz):
    matriz_transposta = matriz.T
    return matriz_transposta

In [6]:
n = int(input("Introuza um valor para a sua matriz: "))
print(n)

3


In [7]:
matriz = np.random.randint(100, size=(n, n))
print(matriz)

[[58  6 94]
 [95  1 71]
 [89 86 96]]


In [9]:
print("A matriz transposta é:")
print(transposta(matriz))

A matriz transposta é:
[[58 95 89]
 [ 6  1 86]
 [94 71 96]]
